# Generated by Django 4.1.3 on 2023-01-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Not required', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Not required', null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Not required', max_length=11, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('msc', 'Moscow'), ('tlt', 'Togliatti'), ('eka', 'Ekaterinburg')], help_text='Required', max_length=35, verbose_name='Region'),
        ),
    ]
