# Generated by Django 4.1.3 on 2023-01-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('Moscow', 'Moscow'), ('Togliatti', 'Togliatti'), ('Ekaterinburg', 'Ekaterinburg')], help_text='Required', max_length=35, verbose_name='Region'),
        ),
    ]
