# Generated by Django 4.1.3 on 2023-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='-', help_text='Required', max_length=11, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('Moscow', 'Moscow'), ('Togliatti', 'Togliatti'), ('Saint Petersburg', 'Saint Petersburg'), ('Ekaterinburg', 'Ekaterinburg')], help_text='Required', max_length=35, verbose_name='Region'),
        ),
    ]
