# Generated by Django 4.1.3 on 2023-01-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.region'),
        ),
    ]
