# Generated by Django 4.1.3 on 2023-01-06 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Content of advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price, rub'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title of advertisement'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of category'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of publication')),
                ('text', models.TextField(max_length=300)),
                ('target_ad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bulletin_board.advertisement')),
            ],
        ),
    ]
