# Generated by Django 4.1.3 on 2023-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0006_alter_advertisement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
