# Generated by Django 4.1.3 on 2023-01-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0007_alter_advertisement_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='target_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='bulletin_board.advertisement'),
        ),
    ]
