# Generated by Django 4.1.3 on 2023-01-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0008_alter_message_target_ad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
