# Generated by Django 4.1.3 on 2023-01-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0010_alter_advertisement_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
