# Generated by Django 4.1.3 on 2022-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0002_category_remove_advertisment_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
