# Generated by Django 4.1.3 on 2022-11-28 02:48

import bulletin_board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0002_alter_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='picture',
            field=models.ImageField(blank=True, upload_to=bulletin_board.models.picture_path),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
