# Generated by Django 4.1.3 on 2022-12-04 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0003_advertisment_picture_user_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
