# Generated by Django 4.1.3 on 2022-12-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0004_advertisment_publication_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_profile',
            new_name='UserProfile',
        ),
    ]
