# Generated by Django 4.1.3 on 2022-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0006_advertisment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
