# Generated by Django 4.1.3 on 2022-12-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0008_region_rename_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.region'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.region'),
        ),
    ]
