# Generated by Django 4.1.3 on 2022-12-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0009_alter_advertisment_region_alter_userprofile_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='region',
        ),
    ]
