# Generated by Django 4.1.3 on 2022-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('msc', 'Moscow'), ('tlt', 'Togliatti'), ('sp', 'Sankt Petersburg')], max_length=35),
        ),
    ]
