# Generated by Django 4.1.3 on 2022-12-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0014_alter_userprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('animals', 'Animals'), ('hobby', 'Hobby'), ('electronics', 'Electronics'), ('toys', 'Toys'), ('auto', 'Auto'), ('real_estate', 'Real estate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('msc', 'Moscow'), ('tlt', 'Togliatti'), ('spb', 'Sankt Petersburg'), ('eka', 'Ekaterinburg')], max_length=35),
        ),
    ]
