# Generated by Django 4.1.3 on 2022-12-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0016_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
