# Generated by Django 4.1.3 on 2022-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0017_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
